
### Configuration stage
stages:
  - build
  - test

FROM runtimeverificationinc/kframework-k:ubuntu-focal-b5d23ac

#image: debian:stable # ocaml/opam:debian-testing-opam

### Configuration section

.build-matrix:
    only: [pushes]
    parallel:
        matrix:
            #- OCAML_VERSION: "4.07.1"
            #- OCAML_VERSION: "4.08.1"
            #- OCAML_VERSION: "4.09.1"
            #- OCAML_VERSION: "4.10.2"
            #- OCAML_VERSION: "4.11.1"
            - OCAML_VERSION: "4.13.1"

preprocessing:
    extends: .build-matrix
    stage: build
    only: [pushes]

    variables:
        FF_USE_FASTZIP: "true"

    script:
        # Obtain and install opam locally.
        - apt-get install wget


        - git clone https://github.com/runtimeverification/k.git
        - cd k/
        - sudo sh install-k

        - sudo wget https://github.com/ocaml/opam/releases/download/2.0.5/opam-2.0.5-x86_64-linux -O /usr/bin/opam
        - sudo chmod 755 /usr/bin/opam
        # Initialize the switch.
        - echo "--- Installation of dependencies"
        - opam init -a --disable-sandboxing --compiler="$OCAML_VERSION"
        - opam update
        - opam switch create "$OCAML_VERSION"
        - eval $(opam env)


        - echo "--- Installation of K"
        - wget https://github.com/runtimeverification/k/releases/download/v5.2.81/kframework_5.2.81_amd64_bullseye.deb
        - sudo apt-get install -y ./kframework_5.2.81_amd64_bullseye.deb

        #- echo "--- Installation of Dedukti"
        #- opam pin add -n -k path dedukti .
        #- opam install --yes --deps-only -d -t dedukti
        #- opam install --yes ocamlformat
        #- opam install --yes tezt --no-checksums --keep-build-dir
        #- opam install --yes ~/.opam/4.13.1/.opam-switch/sources/tezt.1.0.0/tezt/lib


        #- echo "--- Installation of Z3"
        #- sudo apt install --yes libgmp-dev
        #- sudo apt install --yes python3
        #- opam install --yes z3


        - echo "--- Installation of Alt-ergo"
        - sudo apt install --yes libgmp-dev m4 pkg-config autoconf zlib1g-dev
        - opam install --yes alt-ergo.2.3.0
        - eval $(opam env)


        - echo "--- Installation of Lambdapi"
        - opam pin add -n -k path lambdapi .
        - sudo apt --yes install libsigsegv2
        - opam install --yes --deps-only -d -t lambdapi
        - eval $(opam env)
        - why3 config detect


        #- echo "--- Installation of K"
        #- wget https://github.com/runtimeverification/k/releases/download/v5.2.81/kframework_5.2.81_amd64_bullseye.deb
        #- sudo apt-get install --yes ./kframework_5.2.81_amd64_bullseye.deb


        - echo "--- Installation of KaMeLo"
        #- git clone https://gitlab.com/semantiko/kamelo.git
        - cd kamelo
        - make


#test:
#    stage: test
#    only: [pushes] #, merge_requests]
#    script:
#      - make install
#      - echo "running tests..."
#      - make tests
#      - make sanity_check
