on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ocaml-version: [4.13.1] # [4.07.1, 4.08.1, 4.09.1, 4.10.2, 4.11.1]
    runs-on: ubuntu-latest
    steps:
      - name: --- Installation of OPAM
        uses: actions/checkout@v2
      - name: recovering cached opam files...
        uses: actions/cache@v2
        with:
          path: ~/.opam
          key: ${{ runner.os }}-ocaml-${{ matrix.ocaml-version }}
      - name: setting up opam...
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}


      - name: --- Installation of Dedukti
        run: |
          opam update
          opam upgrade
          opam pin add -n -k path dedukti .
          opam install --deps-only -d -t dedukti
          opam install ocamlformat
          opam install tezt --no-checksums --keep-build-dir
          opam install ~/.opam/4.13.1/.opam-switch/sources/tezt.1.0.0/tezt/lib
          opam install z3


      - name: --- Installation of Lambdapi
        run: |
          opam pin add -n -k path lambdapi .
          opam install --deps-only -d -t lambdapi


      - name: --- Installation of K
        run: |
          sudo apt install ./kframework_5.2.81_amd64_focal.deb


      - name: --- Installation of KaMeLo
        run: |
          git clone https://gitlab.com/semantiko/kamelo.git
          cd kamelo
          make
